### PR TITLE
fix host metadata be cached by ConnPool

### LINKED ISSUE #1708: host metadata is cached by connpool
### Describe the bug

Host metadata is cached by ConnPool, so when metadata changes, get HostInfo form requestInfo will return the old metadata.

### Expected behavior

return new host metadata

### Actual behavior

return old host metadata

### Environment

- MOSN Version

### PR DESCRIPTION
**Pull request by Sharember**
### Issues associated with this PR

fix #1708 

### Solutions
You should show your solutions about the issues in your PR, including the overall solutions, details and the changes. At this time, Chinese is allowed to describe these.

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### CODE REVIEW

File: pkg/proxy/downstream.go [hunk 1]
```diff
@@ -1361,7 +1365,7 @@ func (s *downStream) doRetry() {
 	// no reuse buffer
 	atomic.StoreUint32(&s.reuseBuffer, 0)
 
-	pool, err := s.initializeUpstreamConnectionPool(s)
+	host, pool, err := s.initializeUpstreamConnectionPool(s)
```
Comment (taoyuanyuan) [inline pkg/proxy/downstream.go:1368]: should reset requestInfo， meybe we can set reqeustinfo in the func of initializeUpstreamConnectionPool()

**Review by taoyuanyuan — APPROVED** [review]
LGTM

**Review by nejisama — APPROVED** [review]
